# Generated by Django 4.2.7 on 2023-11-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
