# Generated by Django 4.2.7 on 2023-11-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_gpa_student_student_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emails',
            new_name='email',
        ),
    ]
